### PR TITLE
More robust getMediaCount()

### LINKED ISSUE #436: Webp images are not counted as images
So the number given by Kiwix-Serve are wrong, see for example:
image

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #436

### CODE REVIEW

File: src/reader.cpp [hunk 1]
```diff
@@ -120,20 +120,12 @@ unsigned int Reader::getMediaCount() const
...
-  auto it = counterMap.find("image/jpeg");
-  if (it != counterMap.end()) {
-    counter += it->second;
-  }
-
-  it = counterMap.find("image/gif");
-  if (it != counterMap.end()) {
-    counter += it->second;
+  for (auto it = counterMap.begin(); it != counterMap.end(); ++it) {
+    if (it->first.rfind("image/", 0) == 0) {
```
Comment (veloman-yunkan) [inline src/reader.cpp:124]: Better use `kiwix::startsWith()` (declared in `include/tools/stringTools.h`)

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/reader.cpp (hunk 1 above)
Comment (kelson42) [reply src/reader.cpp]: done

**Review by veloman-yunkan — APPROVED** [review]
