### PR TITLE
Fix compilation with libmicrohttpd v0.97.1

### LINKED ISSUE #324: kiwix-serve des not run properly with libmicrohttpd 0.9.64 to 0.9.70 on macOS
See https://bugs.gnunet.org/view.php?id=6090

### LINKED ISSUE #373: Error compiling on arch/artix linux with latest version of libmicrohttpd
I'am trying to compile the AUR package of kiwix-lib but it throws an error while compiling:
```bash
templates/captured_external.html ['templates', 'captured_external_html']
opensearchdescription.xml ['opensearchdescription_xml']
[24/51] Compiling C++ object 'src/25a6634@@kiwix@sha/server.cpp.o'
FAILED: src/25a6634@@kiwix@sha/server.cpp.o 
c++ -Isrc/25a6634@@kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/include/p11-kit-1 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -march=znver1 -m64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -pthread -MD -MQ 'src/25a6634@@kiwix@sha/server.cpp.o' -MF 'src/25a6634@@kiwix@sha/server.cpp.o.d' -o 'src/25a6634@@kiwix@sha/server.cpp.o' -c ../src/server.cpp
../src/server.cpp: In member function ‘bool kiwix::InternalServer::start()’:
../src/server.cpp:248:29: error: invalid conversion from ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)’ {aka ‘int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)’} to ‘MHD_AccessHandlerCallback’ {aka ‘MHD_Result (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)’} [-fpermissive]
  248 |                             &staticHandlerCallback,
      |                             ^~~~~~~~~~~~~~~~~~~~~~
      |                             |
      |                             int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**) {aka int (*)(void*, MHD_Connection*, const char*, const char*, const char*, const char*, long unsigned int*, void**)}
In file included from ../src/server.cpp:39:
/usr/include/microhttpd.h:2428:45: note:   initializing argument 5 of ‘MHD_Daemon* MHD_start_daemon(unsigned int, uint16_t, MHD_AcceptPolicyCallback, void*, MHD_AccessHandlerCallback, void*, ...)’
 2428 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
[35/51] Compiling C++ object 'src/25a6634@@kiwix@sha/server_request_context.cpp.o'
FAILED: src/25a6634@@kiwix@sha/server_request_context.cpp.o 
c++ -Isrc/25a6634@@kiwix@sha -Isrc -I../src -Iinclude -I../include -Istatic -I/usr/include/p11-kit-1 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -march=znver1 -m64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -pthread -MD -MQ 'src/25a6634@@kiwix@sha/server_request_context.cpp.o' -MF 'src/25a6634@@kiwix@sha/server_request_context.cpp.o.d' -o 'src/25a6634@@kiwix@sha/server_request_context.cpp.o' -c ../src/server/request_context.cpp
../src/server/request_context.cpp: In constructor ‘kiwix::RequestContext::RequestContext(MHD_Connection*, std::string, const string&, const string&, const string&)’:
../src/server/request_context.cpp:79:58: error: invalid conversion from ‘int (*)(void*, MHD_ValueKind, const char*, const char*)’ to ‘MHD_KeyValueIterator’ {aka ‘MHD_Result (*)(void*, MHD_ValueKind, const char*, const char*)’} [-fpermissive]
   79 |   MHD_get_connection_values(connection, MHD_HEADER_KIND, &RequestContext::fill_header, this);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                          |
      |                                                          int (*)(void*, MHD_ValueKind, const char*, const char*)
In file included from ../src/server/request_context.h:33,
                 from ../src/server/request_context.cpp:22:
/usr/include/microhttpd.h:2699:49: note:   initializing argument 3 of ‘int MHD_get_connection_values(MHD_Connection*, MHD_ValueKind, MHD_KeyValueIterator, void*)’
 2699 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/server/request_context.cpp:80:64: error: invalid conversion from ‘int (*)(void*, MHD_ValueKind, const char*, const char*)’ to ‘MHD_KeyValueIterator’ {aka ‘MHD_Result (*)(void*, MHD_ValueKind, const char*, const char*)’} [-fpermissive]
   80 |   MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, &RequestContext::fill_argument, this);
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void*, MHD_ValueKind, const char*, const char*)
In file included from ../src/server/request_context.h:33,
                 from ../src/server/request_context.cpp:22:
/usr/include/microhttpd.h:2699:49: note:   initializing argument 3 of ‘int MHD_get_connection_values(MHD_Connection*, MHD_ValueKind, MHD_KeyValueIterator, void*)’
 2699 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
[37/51] Compiling C++ object 'test/9f86d08@@server@exe/server.cpp.o'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x55de324d5450)
```

The same error appears while manually compiling (the newest two releases).

I use the newest version of Artix Linux and would like to use kiwix

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #373
Fixes #324

### CODE REVIEW

File: include/microhttpd_retro.h [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+#define MHD_RESULT enum MHD_Result
+
+#else
+
+/**
+ * Data type to use for functions return an "MHD result".
+ */
+#define MHD_RESULT int
+
+#endif
```
Comment (mgautierfr) [inline include/microhttpd_retro.h:42]: I would have simply does :
```
#if MHD_VERSION < 0x00097002
#define MHD_Result int
#endif
```

This way we simply would have to remove the 3 lines once we don't want compatibility with old libmicrohttpd. And we don't introduce a new identifier.
But I would not block for that.

File: src/server.cpp [hunk 2]
```diff
@@ -248,7 +248,7 @@ bool InternalServer::start() {
                             &staticHandlerCallback,
                             this,
                             MHD_OPTION_SOCK_ADDR, &sockAddr,
-                            MHD_OPTION_THREAD_POOL_SIZE, m_nbThreads,
+                            MHD_OPTION_THREAD_POOL_SIZE, &m_nbThreads,
```
Comment (mgautierfr) [inline src/server.cpp:251]: This seems to be a pretty important change.
Is it a bug on our side or an API change in libmicrohttpd ?
Anyway, the `MHD_RESULT` and `m_nbThreads` are two different changes, please move them in two different commits (with explanation)

Comment (kelson42) [reply src/server.cpp]: Tout a fait, j'ai supprimé ce passage. J'ai un doute toujours, mais je ferai une autre PR si nécessaire.

File: include/microhttpd_retro.h (hunk 1 above)
Comment (kelson42) [reply include/microhttpd_retro.h]: Bien meilleur en effet.

File: include/microhttpd_retro.h [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+ * along with this program; if not, write to the Free Software
+ * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
+ * MA 02110-1301, USA.
+ */
+
+#include <microhttpd.h>
+
+#if MHD_VERSION < 0x00097002
+#define MHD_Result int
+#endif
```
Comment (veloman-yunkan) [inline include/microhttpd_retro.h:24]: microhttpd_retro.h is an internal header, it must be in the src directory.

Comment (veloman-yunkan) [reply include/microhttpd_retro.h:24]: Besides, I would rename it `microhttpd_wrapper.h`

File: include/microhttpd_retro.h [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+ * You should have received a copy of the GNU General Public License
+ * along with this program; if not, write to the Free Software
+ * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
+ * MA 02110-1301, USA.
+ */
+
+#include <microhttpd.h>
+
+#if MHD_VERSION < 0x00097002
+#define MHD_Result int
```
Comment (veloman-yunkan) [inline include/microhttpd_retro.h:23]: using `typedef` instead of `define` should be safer

File: include/microhttpd_retro.h (hunk 3 above)
Comment (kelson42) [reply include/microhttpd_retro.h]: I believe I have fixed both problems now.

File: include/microhttpd_retro.h (hunk 4 above)
Comment (kelson42) [reply include/microhttpd_retro.h]: Done

File: src/server.cpp (hunk 2 above)
Comment (mgautierfr) [reply src/server.cpp]: Beside removing it from the PR, it would be nice to know if there is something wrong in our code.
Passing the value instead of a address is a real bug (if confirmed).

**Comment by kelson42** [comment]
@mgautierfr Thank you. I have squash the 3 commits and will merged.

File: src/server.cpp (hunk 2 above)
Comment (kelson42) [reply src/server.cpp]: I have verified, I think this is perfectly correct, like it is. Sorry.
